# Alban Kraus
# 
# (C) 2016 École nationale des sciences géographiques
# 6-8 avenue Blaise Pascal -- Champs-sur-Marne
# 77455 MARNE-LA-VALLÉE CEDEX2
# FRANCE
# 
# This is free software. You can freely modify and/or distribute it
# under the terms of the GNU General Public License version 3 or
# above.

debug: sensor.c
	gcc -g -Wall -Wextra -o sensor sensor.c -lbcm2835
